transfer: ""
transfer_filename: "large-k-multi-latest.pt"
use_wandb: False
image_size: 128
max_epochs: 2180
batch_size: 2
gradient_accumulation_steps: 16
sample_every_n_steps: 1000
epochs_checkpoint: 5
epochs_checkpoint_save: 50
load_optim_state_from_checkpoint: True
grow: False
combine: False
k_checkpoint_path: ""
use_amp: False
nerf_diff:
  input_size: 128
  color_feat_dim: 16
  depth_size: 64
  a_prob: 0.1
  diff_augmentation_prob: 0.2
  k_diffusion_config: "k_configs/config_128_mid.json"
  lambda_rgb_first: 0.01
  lambda_rgb_other: 1.0
  lambda_opacity: 0.001
  lambda_diffusion: 1.0
  no_cond_prob: 0.1
